version: '3'
services:
  enedis-back:
    image: node:alpine
    working_dir: /usr/src/app
    volumes:
      - ..:/usr/src/app
    command: yarn start
    ports:
      - 3001:3001
    environment:
      - DATABASE_URL=postgres://enedis:password@enedis-db:5432/test
  enedis-db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=enedis
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
